project:
  type: website
  output-dir: docs

website:
  title: "Data Science-AG"
  navbar:
    background: none
    search: false
    left:
      - href: index.qmd
        text: Home
    tools:
      - icon: envelope-at
        text: Eine Frage stellen
        href: "mailto:mail@timnehls.de"
      - icon: github
        text: GitHub Repository
        href: "https://github.com/timnehls/ag-website"
  sidebar: 
    title: "Menü"
    style: floating
    search: true
    contents: 
      - href: index.qmd
        text: Überblick
      - text: "---"
      - section: "1. Einführung in R"
        contents:
        - 01-installation.qmd
        - 02-erste-schritte.qmd
      - text: "---"
      - section: "2. Grundbegriffe"
        contents: 
        - 03-datenstrukturen.qmd
        - 04-funktionen-und-schleifen.qmd
        - 05-visualisierung.qmd
      - text: "---"
      - 06-textdaten.qmd
  repo-url: "https://github.com/timnehls/ag-website"
  repo-actions: [edit, issue]
  reader-mode: false
  
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-overflow: wrap
    code-link: true
    highlight-style: kate
    code-block-bg: "#fefaf1"
  pdf: default

editor: visual

