project:
  type: website
  output-dir: docs

website:
  title: "Data Science-AG"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - "01-einfuehrung.qmd"
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

