project:
  type: website
  output-dir: docs

website:
  title: "Daten-AG"
  navbar:
    background: none
    search: false
    left:
      - href: index.qmd
        text: Home
    tools:
      - icon: envelope-at
        text: Eine Frage stellen
        href: "mailto:mail@timnehls.de"
      - icon: github
        text: GitHub Repository
        menu:
          - text: Sourcecode
            href: "https://github.com/timnehls/ag-website"
          - text: Einen Fehler melden
            href: "https://github.com/timnehls/ag-website/issues"
  sidebar: 
    title: "Menü"
    style: docked
    search: true
    collapse-level: 1
    contents: 
      - href: index.qmd
        text: Überblick
      - text: "---"
      - section: "1. Einführung in R"
        contents:
        - href: 01-installation.qmd
        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

