project:
  type: website
  output-dir: docs

website:
  title: "Data Science-AG"
  navbar:
    left:
      - href: index.qmd
        text: Home
  sidebar: 
    title: "Menü"
    style: docked
    search: true
    collapse-level: 1
    contents: 
      - href: index.qmd
        text: Überblick
      - text: "---"
      - href: 01-einfuehrung.qmd
        text: "1. Einführung in R"
        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

